config/routes.rb
Choose::Application.routes.draw do
  root to: 'confessions#main'

  devise_for :users, :path_names => {:sign_in => "login" } , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/myadmin', :as => 'rails_admin'

  
  
  namespace :admin do
    get "/:path_name" => "confessions#manage"
    root to: "confessions#index"
    
    resources :confessions, :except => [:index,:show] do
      resources :posts, :except => [:index, :show, :new, :update] do
        put "update_approve" => "posts#update_approve"
        put "update_answer" => "posts#update_answer"
      end
    end
  end
  

  get "cfs/:path_name" => "confessions#show", as: 'get_confess'
  
  resources :posts, :only => [:show] do
    put "comment" => "posts#add_comment"
    patch "comment" => "posts#add_comment"

    put "toggle_love" => "posts#toggle_love"
    patch "toggle_love" => "posts#toggle_love"
  end
  
  resources :confessions, :only => [:show] do
    put "add_post" => "confessions#add_post"
    patch "add_post" => "confessions#add_post"

    put "toggle_love" => "confessions#toggle_love"
    patch "toggle_love" => "confessions#toggle_love"
  end


  get "contact" => "contact#index"
  

end

app/models/confession.rb
class Confession
  include Mongoid::Document
  include Loveable

  field :title, type: String
  field :text, type: String
  field :path_name, type: String
  
  # mount_uploader :banner, ImageUploader

  # Relationship #
  ################

  has_many :posts, dependent: :destroy
  belongs_to :user, index: true
  accepts_nested_attributes_for :posts

  #validate
  validates_presence_of :title, :path_name
  validates_uniqueness_of :path_name

  before_create :set_default_value


  def get_by_index(search_index)
    self.posts.approved.where(:index => search_index)
  end

  def get_by_newest(offset, limit)
    self.posts.approved.desc(:index).skip(offset).limit(limit)
  end

  def get_by_hottest(offset, limit)
    self.posts.approved.desc(:total_love).skip(offset).limit(limit)
  end

  protected


  def self.find_by_pathname(pathname)
    self.where(:path_name => pathname).first
  end

  def self.find_by_pathname_and_user(pathname, user_id)
    self.where(:path_name => pathname, :user_id => user_id).first
  end

  def set_default_value
    self.love_users = []
  end
 
end

app/controllers/admin/confessions_controller.rb
class Admin::ConfessionsController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!

  # GET /confessions
  # GET /confessions.json
  def index
    @confessions = Confession.where(:user_id => current_user._id)
    respond_to do |format|
      format.html # index.html.erb
    end
  end


  def manage
    @confession = Confession.find_by_pathname_and_user(params[:path_name], current_user._id)
    @posts = Post.where(:confession_id => @confession._id)
    @approved_posts = []
    @not_approved_posts = []
    @posts.each do |post|
      if post.approved == true
        @approved_posts << post
      else
        @not_approved_posts << post
      end
    end
    respond_to do |format|
      format.html
    end
  end

  # GET /confessions/new
  # GET /confessions/new.json
  def new
    @confession = Confession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @confession }
    end
  end

  # GET /confessions/1/edit
  def edit
    @confession = Confession.find(params[:id])
  end

  # POST /confessions
  # POST /confessions.json
  def create
    @confession = Confession.new(confession_params)
    @confession.user = current_user

    respond_to do |format|
      if @confession.save
        format.html { redirect_to admin_root_path, notice: 'Confession was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PATCH/PUT /confessions/1
  # PATCH/PUT /confessions/1.json
  def update
    @confession = Confession.find(params[:id])

    respond_to do |format|
      if @confession.update_attributes(confession_params)
        format.html { redirect_to admin_root_path, notice: 'Confession was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @confession.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /confessions/1
  # DELETE /confessions/1.json
  def destroy
    @confession = Confession.find(params[:id])
    @confession.destroy

    respond_to do |format|
      format.html { redirect_to admin_confessions_url }
      format.json { head :no_content }
    end
  end

  private

    def confession_params
      main_param = params.require(:confession).permit(:title, :text, :path_name);
    end


end

app/controllers/confessions_controller.rb
class ConfessionsController < ApplicationController
  layout "store"
  
  include LoveableController
  before_filter :authorize_actions
  before_filter :get_post_by_filter , :only => [:show]
  before_filter :get_more_posts , :only => [:view_more]

  # GET /                    #
  # The page for introducing #
  ############################
  def main
    respond_to do |format|
      format.html # index.html.erb
    end
  end


  # GET /path_name                  #
  # The page for showing confession #
  ###################################
  def show
    # for each post
    @post_decorator = PostDecorator.new

    respond_to do |format|
      format.html # show.html.erb
    end
  end


  # PUT confession/:confession_id/add_post
  # Add additional station tests for existing device

  def add_post
    @confession = Confession.find(params[:confession_id])

    if @confession.nil?
      flash[:error] = "Sorry, this post is invalid."
      return
    end

    confession_post = @confession.posts.build(add_post_params)
    if confession_post.save
      flash[:success] = "Sucessfully"
    else
      flash[:error] = "Sorry, this post is invalid."
    end

    respond_to do |format|
      format.html { redirect_to root_path + @confession.path_name }
    end
  end




  ## POST /love_confession
  ## params: confession_id

  def toggle_love
    @confession_id = love_params[:confession_id]
    @confession = Confession.find(@confession_id)

    toggle_love_by_user(@confession, current_user._id)

    respond_to do |format|
      format.js {}
    end
  end


  private
    # for love cofession
    #
    def love_params
      params.permit(:confession_id)
    end


    def confession_params
      main_param = params.require(:confession).permit(:title, :text, :banner, :banner_cache)
    end


    def add_post_params
      main_params = params.require(:confession).permit(:title, :text, :email)
    end

    def get_post_by_filter
      @confession = Confession.find_by_pathname(params[:path_name])
      @approved_posts =
      if params[:by_index]
        @confession.get_by_index( params[:by_index] )
      elsif params[:by_newest]
        @view_more_param = { :by_newest => params[:by_newest].to_i + 20 }
        @confession.get_by_newest( params[:by_newest] , 20 )
        
      elsif params[:by_hottest]
        @view_more_param = { :by_hottest => params[:by_hottest].to_i }
        @confession.get_by_hottest( params[:by_hottest], 20)
      else
        @view_more_param = { :by_newest => params[:by_newest].to_i + 20 }
        @confession.get_by_newest( params[:by_newest] , 20 )  
      end
    end


    ##
    # Authorize user

    def authorize_actions
      unless user_signed_in?
        @is_admin = true;
      else
        @is_admin = false;
      end
    end
end

app/views/confessions/_filter_control.html.erb
    <dl class="sub-nav" data-topbar data-options="sticky_on: medium;">
      <div class="filter-wrap">
        <div class="row">
          <div class="large-6 columns filter-dropdown">
            <span>Filter:</span>
            <span>
              <a href="#" data-dropdown="drop-filter" data-options="is_hover:true" class="m-0 small secondary radius round button dropdown">Choose filter</a><br>
              <ul id="drop-filter" data-dropdown-content class="f-dropdown">
                <li>
                  <%= link_to "Newest", get_confess_path(:path_name => @confession.path_name, :by_newest => true) %>
                </li>
                <li>
                  <%= link_to "Hottest", get_confess_path(:path_name => @confession.path_name, :by_hottest => true) %>
                </li>
              </ul>
            </span>
          </div>
          <div class="large-6 columns filter-search">
                <%= form_tag(@confession.path_name, method: "get") do %>
                  <div class="search-wrap radius-20 right">
                    <a class="fa fa-search button-submit" id="search-button" name="commit" type="submit" ></a>
                    <%= text_field_tag(:by_index, nil, placeholder: "Index", class: "search-input remove-select") %>
                  </div>
                <% end %>
          </div>
        </div>   
      </div>
    </dl>

app/views/confessions/_post_create_form.html.erb
  <div class="large-6 columns compose-div" >
    <%= form_for @confession, :url => confession_add_post_path(@confession) do |f| %>
      <div class="clearfix">
        <%= f.text_area :text, :id => "confession_post_text", :class => "post-area full-width", :placeholder => "Compose your post" , :value => "" %>
      </div>
      <div class="clearfix ask-panel radius"> 
        <button type="submit" class="small radius radius right ask-button m-0">
          <i class="fa fa-pencil action-icon"></i>
          Confess
        </button>
      </div>
    <% end %>
  </div>

app/views/confessions/_post_timeline_item.html.erb
<li class="timeline-item radius-5">

  <div class="content-inner">
    <div class="row">
      <div class="columns">
        <% if user_signed_in? %> 
          <%= render "partials/posts/post_love_button" %>
        <% end %>
      </div>
      <div class="columns item-content p-0">
        <div class="row collapse">
          <a href="<%= post_path(@post_decorator.id) %>">
            <div class="large-11 columns p-0 item-text">
              <span class="label round alert"><%= @post_decorator.index %></span>
              <p class="lh150 question">
                <%= @post_decorator.text.gsub("\n" , "<br/>").try(:html_safe) %>
              </p>
              
              <% if @post_decorator.answer.present? %>
                <p class="lh150 answer">
                  <span class="orange-text admin-answer">Feedback:<br/></span>
                  <%= @post_decorator.answer.gsub("\n" , "<br/>").try(:html_safe) %>
                </p>
              <% end %>
              <hr>
            </div>
          </a>
        </div>

        <div class="row collapse">
          <div class="large-11 columns p-0 post-info">
            <%= render "partials/posts/post_info" %>
          </div>
        </div>
      </div>
    </div>

  </div>
</li>

app/views/confessions/main.html.erb
<!-- HTML -->
<section id="slide-1" class="homeSlide">
    <div class="bcg"
        data-center="background-position: 50% 0px;"
        data-top-bottom="background-position: 50% -100px;"
        data-anchor-target="#slide-1"
    >
        <div class="hsContainer">
            <div class="hsContent"
                data-center="opacity: 1"
                data-106-top="opacity: 0"
                data-anchor-target="#slide-1 h2"
            >
                <h2>Fade out elements before they leave viewport</h2>
            </div>
        </div>
    </div>
</section>


<!-- HTML -->
<section id="slide-2">
    <div class="bcg"
        data-0="background-color:rgb(1,27,59);"
        data-top="background-color:(0,0,0);"
        data-anchor-target="#slide-2"
    >
        <div class="hsContainer">
            <div class="hsContent">
                <h2
                    data--200-bottom="opacity: 0"
                    data-center="opacity: 1"
                    data-206-top="opacity: 1"
                    data-106-top="opacity: 0"
                    data-anchor-target="#slide-2 h2"
                >
                    Fade me in and out
                </h2>
            </div>
        </div>
    </div>
</section>


<!-- HTML -->
<section id="slide-3" class="homeSlide">
    <div class="bcg"
        data-center="background-position: 0px 50%;"
        data-bottom-top="background-position: 0px 40%;"
        data-top-bottom="background-position: -40px 50%;"
        data-anchor-target="#slide-3"
    >
        <div class="hsContainer">
            <div class="hsContent">
                <div class="plaxEl"
                    data-106-top="opacity: 0"
                    data-bottom="opacity: 0; position: fixed; top: 206px; width: 100%; left: 0;"
                    data--30p-top="opacity: 1;"
                    data--60p-top="opacity: 0;"
                    data-anchor-target="#slide-3"
                >
                    <h2>Fixed element fading in and out</h2>
                </div>
            </div>
    	</div>
    </div>
</section>


<!-- HTML -->
<section id="slide-4" class="homeSlide homeSlideTall">
    <div class="bcg"
        data-center="background-position: 50% 0px;"
        data-bottom-top="background-position: 50% 100px;"
        data-top-bottom="background-position: 50% -100px;"
        data-anchor-target="#slide-4"
    >
        <div class="curtainContainer">
            <div class="curtain"
                data-bottom-top="opacity: 1"
                data-106-top="height: 1%; top: -10%; opacity: 0;"
                data-center="height: 100%; top: 0%; opacity: 0.5"
                data-anchor-target="#slide-4"
            ></div>
            <div class="copy"
                data-bottom-top="opacity: 0"
                data--100-bottom="opacity: 0"
                data--280-bottom="opacity: 1;"
                data-280-top="opacity: 1;"
                data-106-top="opacity: 0;"
                data-anchor-target="#slide-4 .copy"
            >
                <h2>Curtain effect while you scroll</h2>
            </div>

        </div>
    </div>
</section>



<!-- HTML -->
<section id="slide-5" class="homeSlide homeSlideTall2">
    <div class="bcg">&nbsp;</div>
    <div class="bcg bcg2"
        data-bottom-top="opacity: 0;"
        data--33p-top="opacity: 0;"
        data--66p-top="opacity: 1;"
        data-anchor-target="#slide-5"
    >
        <div class="hsContainer">
            <div class="hsContent"
                data-bottom-top="opacity: 0;"
                data-center="opacity: 1"
                data-anchor-target="#slide-5"
            >
                <h2>Fixed element fading in and out</h2>
            </div>
        </div>
    </div>
    <div class="bcg bcg3"
        data-300-bottom="opacity: 0;"
        data-100-bottom="opacity: 1;"
        data-anchor-target="#slide-5"
    >
        <div class="hsContainer">
            <div class="hsContent"
                data-100-bottom="opacity: 0;"
                data-bottom="opacity: 1;"
                data-anchor-target="#slide-5"
            >
                <h2>The End</h2>
            </div>
    	</div>
    </div>
</section>

app/views/confessions/show.html.erb
<div class="row collapse">
  <div class="large-12 columns">

    <%= render "partials/sessions/alert_bar" %>
    
    <!-- Header -->
    <header class="clearfix radius-5 header antialiased">
      <div class="row collapse">
        <div class="large-12 columns">
          
          <%= render "partials/sessions/dashboard" %>
          <%= render 'post_create_form' %>
         
        </div>
      </div>
    </header>
     
    <!-- BUTTON GROUP -->
    <div class="content-wrap">
      <div class="row collapse">
        <div class="large-12 columns">

          <%= render "filter_control" %>

          <!-- Timeline posts -->
          <section class="main">
            <ul class="timeline m-0">
              <% @approved_posts.each do |post| %>
                <% @post_decorator.setPost(post) %>
                <%= render "post_timeline_item", :post => post %>
              <% end %>

              
            </ul>
            <div class="text-center">
              <a class="button secondary radius round uppercase" href="<%= get_confess_path( { :path_name => @confession.path_name }, @view_more_param) %>"> View more ... </a>
            </div>

          </section>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/confessions/toggle_love.js.erb
(function (){
  var love_button = $("#<%= @confession_id %>_confession_love_submit");
  love_button.removeClass('disable');
  <% if @is_loved %>
    love_button.addClass('love-active');
  <% else %>
    love_button.removeClass('love-active');
  <% end %>
})();