config/routes.rb
Choose::Application.routes.draw do
  root to: 'confessions#main'

  devise_for :users, :path_names => {:sign_in => "login" } , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/myadmin', :as => 'rails_admin'

  
  
  namespace :admin do
    get "/:path_name" => "confessions#manage"
    root to: "confessions#index"
    
    resources :confessions, :except => [:index,:show] do
      resources :posts, :except => [:index, :show, :new, :update] do
        put "update_approve" => "posts#update_approve"
        put "update_answer" => "posts#update_answer"
      end
    end
  end
  

  get "cfs/:path_name" => "confessions#show", as: 'get_confess'
  
  resources :posts, :only => [:show] do
    put "comment" => "posts#add_comment"
    patch "comment" => "posts#add_comment"

    put "toggle_love" => "posts#toggle_love"
    patch "toggle_love" => "posts#toggle_love"
  end
  
  resources :confessions, :only => [:show] do
    put "add_post" => "confessions#add_post"
    patch "add_post" => "confessions#add_post"

    put "toggle_love" => "confessions#toggle_love"
    patch "toggle_love" => "confessions#toggle_love"
  end


  get "contact" => "contact#index"
  

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Loveable
  include Approveable

  field :title, type: String
  field :text, type: String
  field :email_sender, type: String
  
  field :answer, type: String

  field :watch, type: Integer
  field :index, type: Integer
  

  # Relationship #
  ################

  belongs_to :confession
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments

  # callback #
  ############

  after_build :set_default_value

  def build_comment(current_user_id, comment)
    comment_post = self.comments.build({:text => comment, :user_id => current_user_id})
    comment_post.save
  end


  protected

  # Set default value when create #
  #################################
  def set_default_value
    self.answer = ""
    self.approved = false
    self.watch = 0
    self.love_users = []
  end





end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout "admin"
  before_filter :authorize_actions

  # DELETE /posts/1
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_path(@post.confession.path_name)  }
    end
  end


  def update_approve
    @post = Post.find(params[:post_id])
    
    if @post.present? and @post.set_approve(params[:is_previous_approve])
      # Success: TO-DO
    end

    respond_to do |format|
      format.js {}
    end
  end


  def update_answer
    @post = Post.find(params[:post_id])
    
    if @post.present? and @post.update_attributes(:answer => params[:answer])
      # Success: TO-DO  
    end

    respond_to do |format|
      format.js {}
    end
  end

  private
    ##
    # Authorize user
    def authorize_actions
      unless user_signed_in?
        @is_admin = true;
      else
        @is_admin = false;
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include LoveableController
  before_filter :authenticate_user! , :except => [:show]
  
  ## POST /love_post
  ## params: post_id

  def toggle_love
    @post = Post.find(love_params[:post_id])

    @post_decorator = PostDecorator.new
    @post_decorator.setPost(@post)

    toggle_love_by_user(@post, current_user._id)

    respond_to do |format|
      format.js {}
    end

  end



  def add_comment
    @post_id = comment_params[:post_id]
    @comment = comment_params[:comment]
    post = Post.find(@post_id)
    
    unless post.nil?
      if post.build_comment(current_user._id, @comment)
        # TO-DO
      else
        # TO-DO
      end
    end

    respond_to do |format|
      format.js {}
    end

  end

  def show
    @post = Post.find(params[:id])
    
    @post_decorator = PostDecorator.new
    @post_decorator.setPost(@post)

    respond_to do |format|
      format.html # show.html.erb
    end
  end


  private
  def love_params
    params.permit(:post_id)
  end

  def comment_params
    params.permit(:post_id, :user_id, :comment)
  end

  

end

app/views/partials/posts/_post_info.html.erb
<div class="row collapse">
  <session class="large-8 columns rating-section">
    <i class="fa fa-clock-o"></i>
    <span class="icon-val light-gray-color"><%= @post_decorator.watch %></span>

    <i class="fa fa-eye"></i>
    <span class="icon-val light-gray-color"><%= @post_decorator.watch %></span>

    <i class="fa fa-comment-o"></i>
    <span class="icon-val light-gray-color"><fb:comments-count href="<%= post_url(@post_decorator.id) %>"</fb:comments-count> <%= @post_decorator.total_comments %></span>

    <i class="fa fa-heart-o"></i>
    <span class="icon-val light-gray-color"><%= @post_decorator.total_love_users %></span>
  </session>

  <session class="large-4 columns sharing-section">
    <div class="right">
      <div class="fb-like" data-href="<%= post_url(@post_decorator.id) %>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
      <div class="custom-tweet-button">
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= post_url(@post_decorator.id) %>" data-via="your_screen_name" data-lang="en">Tweet</a>
      </div>
    </div>
  </session>
</div>

app/views/partials/posts/_post_love_button.html.erb
<%= form_tag( post_toggle_love_path(@post_decorator.id) , method: :put, :remote => true, :id => @post_decorator.love_form_id ) do %>
  <a name="commit" type="submit" class="relative <%= @post_decorator.love_classes(current_user._id) %>" value="" id="<%= @post_decorator.love_submit_id %>" >
    <div class="relative love-button-wrap remove-select">
      <div class="love-bg absolute radius-10">
      </div>
      <div class="absolute">
        <i class="relative heart-ico fa fa-heart-o p-0"></i>
      </div>
    </div>
  </a>
<% end %>