config/routes.rb
Choose::Application.routes.draw do
  root to: 'confessions#main'

  devise_for :users, :path_names => {:sign_in => "login" } , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/myadmin', :as => 'rails_admin'

  
  
  namespace :admin do
    get "/:path_name" => "confessions#manage"
    root to: "confessions#index"
    
    resources :confessions, :except => [:index,:show] do
      resources :posts, :except => [:index, :show, :new, :update] do
        put "update_approve" => "posts#update_approve"
        put "update_answer" => "posts#update_answer"
      end
    end
  end
  

  get "cfs/:path_name" => "confessions#show", as: 'get_confess'
  
  resources :posts, :only => [:show] do
    put "comment" => "posts#add_comment"
    patch "comment" => "posts#add_comment"

    put "toggle_love" => "posts#toggle_love"
    patch "toggle_love" => "posts#toggle_love"
  end
  
  resources :confessions, :only => [:show] do
    put "add_post" => "confessions#add_post"
    patch "add_post" => "confessions#add_post"

    put "toggle_love" => "confessions#toggle_love"
    patch "toggle_love" => "confessions#toggle_love"
  end


  get "contact" => "contact#index"
  

end

app/models/confession.rb
class Confession
  include Mongoid::Document
  include Loveable

  field :title, type: String
  field :text, type: String
  field :path_name, type: String
  
  # mount_uploader :banner, ImageUploader

  # Relationship #
  ################

  has_many :posts, dependent: :destroy
  belongs_to :user, index: true
  accepts_nested_attributes_for :posts

  #validate
  validates_presence_of :title, :path_name
  validates_uniqueness_of :path_name

  before_create :set_default_value


  def get_by_index(search_index)
    self.posts.approved.where(:index => search_index)
  end

  def get_by_newest(offset, limit)
    self.posts.approved.desc(:index).skip(offset).limit(limit)
  end

  def get_by_hottest(offset, limit)
    self.posts.approved.desc(:total_love).skip(offset).limit(limit)
  end

  protected


  def self.find_by_pathname(pathname)
    self.where(:path_name => pathname).first
  end

  def self.find_by_pathname_and_user(pathname, user_id)
    self.where(:path_name => pathname, :user_id => user_id).first
  end

  def set_default_value
    self.love_users = []
  end
 
end

app/controllers/admin/confessions_controller.rb
class Admin::ConfessionsController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!

  # GET /confessions
  # GET /confessions.json
  def index
    @confessions = Confession.where(:user_id => current_user._id)
    respond_to do |format|
      format.html # index.html.erb
    end
  end


  def manage
    @confession = Confession.find_by_pathname_and_user(params[:path_name], current_user._id)
    @posts = Post.where(:confession_id => @confession._id)
    @approved_posts = []
    @not_approved_posts = []
    @posts.each do |post|
      if post.approved == true
        @approved_posts << post
      else
        @not_approved_posts << post
      end
    end
    respond_to do |format|
      format.html
    end
  end

  # GET /confessions/new
  # GET /confessions/new.json
  def new
    @confession = Confession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @confession }
    end
  end

  # GET /confessions/1/edit
  def edit
    @confession = Confession.find(params[:id])
  end

  # POST /confessions
  # POST /confessions.json
  def create
    @confession = Confession.new(confession_params)
    @confession.user = current_user

    respond_to do |format|
      if @confession.save
        format.html { redirect_to admin_root_path, notice: 'Confession was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PATCH/PUT /confessions/1
  # PATCH/PUT /confessions/1.json
  def update
    @confession = Confession.find(params[:id])

    respond_to do |format|
      if @confession.update_attributes(confession_params)
        format.html { redirect_to admin_root_path, notice: 'Confession was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @confession.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /confessions/1
  # DELETE /confessions/1.json
  def destroy
    @confession = Confession.find(params[:id])
    @confession.destroy

    respond_to do |format|
      format.html { redirect_to admin_confessions_url }
      format.json { head :no_content }
    end
  end

  private

    def confession_params
      main_param = params.require(:confession).permit(:title, :text, :path_name);
    end


end

app/controllers/confessions_controller.rb
class ConfessionsController < ApplicationController
  layout "store"
  
  include LoveableController
  before_filter :authorize_actions
  before_filter :get_post_by_filter , :only => [:show]
  before_filter :get_more_posts , :only => [:view_more]

  # GET /                    #
  # The page for introducing #
  ############################
  def main
    respond_to do |format|
      format.html # index.html.erb
    end
  end


  # GET /path_name                  #
  # The page for showing confession #
  ###################################
  def show
    # for each post
    @post_decorator = PostDecorator.new

    respond_to do |format|
      format.html # show.html.erb
    end
  end


  # PUT confession/:confession_id/add_post
  # Add additional station tests for existing device

  def add_post
    @confession = Confession.find(params[:confession_id])

    if @confession.nil?
      flash[:error] = "Sorry, this post is invalid."
      return
    end

    confession_post = @confession.posts.build(add_post_params)
    if confession_post.save
      flash[:success] = "Sucessfully"
    else
      flash[:error] = "Sorry, this post is invalid."
    end

    respond_to do |format|
      format.html { redirect_to root_path + @confession.path_name }
    end
  end




  ## POST /love_confession
  ## params: confession_id

  def toggle_love
    @confession_id = love_params[:confession_id]
    @confession = Confession.find(@confession_id)

    toggle_love_by_user(@confession, current_user._id)

    respond_to do |format|
      format.js {}
    end
  end


  private
    # for love cofession
    #
    def love_params
      params.permit(:confession_id)
    end


    def confession_params
      main_param = params.require(:confession).permit(:title, :text, :banner, :banner_cache)
    end


    def add_post_params
      main_params = params.require(:confession).permit(:title, :text, :email)
    end

    def get_post_by_filter
      @confession = Confession.find_by_pathname(params[:path_name])
      @approved_posts =
      if params[:by_index]
        @confession.get_by_index( params[:by_index] )
      elsif params[:by_newest]
        @view_more_param = { :by_newest => params[:by_newest].to_i + 20 }
        @confession.get_by_newest( params[:by_newest] , 20 )
        
      elsif params[:by_hottest]
        @view_more_param = { :by_hottest => params[:by_hottest].to_i }
        @confession.get_by_hottest( params[:by_hottest], 20)
      else
        @view_more_param = { :by_newest => params[:by_newest].to_i + 20 }
        @confession.get_by_newest( params[:by_newest] , 20 )  
      end
    end


    ##
    # Authorize user

    def authorize_actions
      unless user_signed_in?
        @is_admin = true;
      else
        @is_admin = false;
      end
    end
end

app/views/admin/confessions/_filter_post.html.erb
<dl class="sub-nav" data-topbar data-options="sticky_on: medium;">
  <div class="filter-wrap">
    <div class="row collapse">
      <div class="large-6 columns filter-dropdown">
        <span>Filter:</span>
        <span>
          <a href="#" data-dropdown="drop-filter" data-options="is_hover:true" class="m-0 tiny secondary radius round button dropdown">Dropdown Button</a><br>
          <ul id="drop-filter" data-dropdown-content class="f-dropdown tabs">
            <li class="active">
              
              <a href="#panel2-1">All</a>
            </li>
            <li>
              <a href="#panel2-2">Approved</a>
            </li>
            <li>
              <a href="#panel2-3">Not-Approved</a>
            </li>
          </ul>
        </span>
      </div>
    </div>   
  </div>
</dl>

app/views/admin/confessions/_form.html.erb
<%= form_for @confession, :url => {:action => @confession.new_record? ? :create : :update} do |f| %>

  <% if @confession.errors.any? %>
    <div id="error_explanation">
      <p><small><%= pluralize(@confession.errors.count, "error") %> prohibited this confession from being saved:</small></p>
      <ul>
      <% @confession.errors.full_messages.each do |msg| %>
        <li><small><%= msg %></small></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>
  <div>
    <%= f.label :path_name %>
    <%= f.text_field :path_name %>
  </div>
  <button type="submit" class="radius">Submit</button>


<% end %>

app/views/admin/confessions/_posts_table.html.erb
<div class="row">
    <section class="panel radius white-bg callout-border">
        <div>
            <i class="fa fa-th"></i>
            <span class="dashboard-icon-val">Your posts</span>
        </div>


        <table class="admin_table"> 
            <thead>
                <tr>
                    <th>#</th>
                    <th>Post</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <% posts_table.each_with_index do |post, index| %>
                <tr>
                
                    <td><%= post.index %></td>
                    <td>
                        <p class="question"><%= post.text.gsub("\n" , "<br/>").try(:html_safe) %></p>
                        <hr/>
                        <h4 class="feedback-text green"><strong>Admin's feedback:</strong></h4>

                        <div class="clearfix" id="answer-div-<%= post._id %>">
                            <% if post.answer.present? %>
                                <div class="answer">
                                    <p class="m0"><%= post.answer.gsub("\n" , "<br/>").try(:html_safe) %></p>
                                </div>
                            <% else %>
                                <a class="feedback-btn button radius tiny success " data-id="<%= post._id %>">
                                    <i class="fa fa-trash-o action-icon"></i>
                                    <span class="action-icon-val">
                                        <%= post.answer.present? ? "Edit feedback" : "Add feedback" %>
                                    </span>
                                </a>
                            <% end %>
                         </div>
                        <div class="clearfix feedback-form hide" id="feedback-form-<%= post._id %>" >

                            <%= form_tag( admin_confession_post_update_answer_path(:confession_id => post.confession._id  ,:post_id => post._id) , method: :put, :remote => true, :html => {:class => "clearfix"} ) do %>
                                <%= text_area_tag "answer", nil, :class => "answer" %>
                                <%= submit_tag "Submit", :class => "button mbt10 radius success right" %>
                               
                                <a class="feedback-cancel-btn button mbt10 mr10 radius success right" data-id="<%= post._id %>" >Cancel</a>
                                
                            <% end %>
                        </div>
                   
                    </td>
                    <td class="no-select">
                        <%= form_tag( admin_confession_post_update_approve_path(:confession_id => post.confession._id  ,:post_id => post._id) , method: :put, :remote => true ) do %>
                            <div class="switch round small switch-button">
                                <input id="switchName<%= index %>" type="checkbox" name="is_previous_approve" value="yes"<% if post.approved? %> checked <% end %> >
                                <label for="switchName<%= index %>" ></label>
                            </div>
                        <% end %>
                    </td>
                    
                    <td>
                        <a class="feedback-btn button radius tiny success" data-id="<%= post._id %>">
                            <i class="fa fa-trash-o action-icon"></i>
                            <span class="action-icon-val">
                                <%= post.answer.present? ? "Edit feedback" : "Add feedback" %>
                            </span>
                        </a>

                        <a class="button radius tiny alert admin-button" data-method="delete" href="<%= admin_confession_post_path(:confession_id => post.confession._id  ,:id => post._id) %>" rel="nofollow">
                            <i class="fa fa-trash-o action-icon"></i>
                            <span class="action-icon-val"></span>
                        </a>

                        
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </section>
</div>

app/views/admin/confessions/edit.html.erb
<h1>Editing confession</h1>

<%= render 'form' %>

<%= link_to 'Back To Zone', admin_root_path , :class => "button" %>

app/views/admin/confessions/index.html.erb
<%= render "partials/sessions/admin_dashboard" %> 
<div class="row mt-20">
  <section class="panel radius border-blue">
    <div>
      <i class="fa fa-th"></i>
      <span class="dashboard-icon-val">Your pages</span>
    </div>
    <table class="admin_table">
      <thead>
        <th>Title</th>
        <th>Text</th>
        <th>Path</th>
        <th>Action</th>
      </thead>

      <% @confessions.each do |confession| %>
      <tr>
        <td><%= confession.title %></td>
        <td><%= confession.text %></td>
        <td><%= confession.path_name %></td>
        <td>
          <a class="button radius tiny success admin-button" href="admin/<%= confession.path_name %>">
            <i class="fa fa-cogs action-icon"></i>
            <span class="action-icon-val">Manage</span>
          </a>
          
          <a class="button radius tiny primary admin-button" href="/<%= confession.path_name %>">
            <i class="fa fa-arrow-circle-o-up action-icon"></i>
            <span class="action-icon-val">Show</span>
          </a>
          
          <a class="button radius tiny blue-button admin-button" href="<%= edit_admin_confession_path(confession) %>">
            <i class="fa fa-pencil-square-o action-icon"></i>
            <span class="action-icon-val">Edit</span>
          </a>


          <a class="button radius tiny alert admin-button" data-confirm="Are you sure?" data-method="delete" href="<%= admin_confession_path(confession) %>" rel="nofollow">
            <i class="fa fa-trash-o action-icon"></i>
            <span class="action-icon-val">Destroy</span>
          </a>

        </td>
      </tr>
      <% end %>
    </table>

    <a class="button radius success" href="new_admin_confession_path">
      <i class="fa fa-plus action-icon"></i>
      New Page
    </a>
  </section>
</div>

app/views/admin/confessions/manage.html.erb
<header class="clearfix radius-5 header antialiased">
  <div class="clearfix row ">
    <div class="large-6 columns">
      <div>
        <h3><strong><%= @confession.title %></strong></h3>
        <p><%= @confession.text %></p>
      </div>
    </div>
    <div class="large-6 columns text-center">
      <h3 class="black-text">Actions</h3>
      <div class="row">
        <div class="large-4 columns left text-center">
          <a class="admin-action-button" href="/<%= @confession.path_name %>">
            <i class="fa  fa-external-link dashboard-icon"></i>
            <p class="dashboard-icon-val uppercase">Show</p>
          </a>
        </div>
        <div class="large-4 columns left text-center">
          <a class="admin-action-button" href="<%= edit_admin_confession_path(@confession) %>">
            <i class="fa fa-cog dashboard-icon"></i>
            <p class="dashboard-icon-val  uppercase">Edit</p>
          </a>
        </div>
        <div class="large-4 columns left text-center">
          <a class="admin-action-button" href="<%= admin_root_path %>">
            <i class="fa fa-mail-reply dashboard-icon"></i>
            <p class="dashboard-icon-val uppercase">Back To Admin</p>
          </a>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="row admin-page">

  <dl class="tabs" data-tab>
    <dd class="active"><a href="#panel2-1">All</a></dd>
    <dd><a href="#panel2-2">Approved</a></dd>
    <dd><a href="#panel2-3">Not-Approved</a></dd>
  </dl>


  <div class="tabs-content">
    <div class="content active" id="panel2-1">
      <%= render partial:"posts_table", object: @posts %>
    </div>
    <div class="content" id="panel2-2">
      <%= render partial:"posts_table", object: @approved_posts %>
    </div>
    <div class="content" id="panel2-3">
      <%= render partial:"posts_table", object: @not_approved_posts %>
    </div>
  </div>

  <%= link_to 'Back', admin_root_path , :class => "button" %>

</div>

app/views/admin/confessions/new.html.erb
<section class="panel radius">
    <div>
      <i class="fa fa-th"></i>
      <span class="dashboard-icon-val">New page </span>
    </div>
  
    <%= render 'form' %>

    <%= link_to 'Back', admin_root_path , :class => "button radius secondary" %>
</section>